# Generated by Django 3.2.21 on 2023-09-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoListApp', '0003_remove_extenduser_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='images',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
